### PR TITLE
rewrite: subscribed channels, complete refactor, pep8 formatting, switch from python2 to python3, and more!

### PR DESCRIPTION
**Pull request by adtac**
Hey @LeftyBC. Great plugin! I spent a couple of hours refactoring the whole code when I wanted to add a new feature (subscribing to channels: lets you get notifications for **all** messages in a channel irrespective of whether or not you're highlighted).

I'll try to summarise the list of changes:
 - Ported the code to python3 (see https://weechat.org/scripts/python3/)
 - Refactored a lot of code and reduced redundant code
 - Formatted the whole thing to follow PEP8 to an extent (not restricting myself to 80 chars though)
 - Added `subscribe` and `unsubscribe` commands
 - Bumped up the version to 0.6

There is a bit of an API change (rephrased some things); see the README for more information. But since weebullet is still in 0.x (beta software), I think it's okay to change the API without too many consequences.

I know that these are huge changes, so I'll completely understand if you do not want to merge these changes in; I will be maintaining my own fork of that's the case. I'm also submitting the new script to https://weechat.org/scripts.

### CODE REVIEW

**Comment by adtac** [comment]
@LeftyBC are you still maintaining this project? Just curious :)

**Comment by LeftyBC** [comment]
I am! Haven't had a chance to check out the PR, but I'll take a look as
soon as I can!

Cheers,
Lefty

**Comment by adtac** [comment]
No problem! Thanks a lot!

**Comment by LeftyBC** [comment]
Apologies for taking so long to merge this - the usual excuses about life etc. apply.  A second PR to update to py3 support showing up is what reminded me!

**Pull request merged**
